/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:03630ed4-d6cf-4b63-a72e-3babefbbe1cf",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uc8NTFC0c",
    "aws_user_pools_web_client_id": "2ckurifocab7ie720f3jrsvhpi",
    "oauth": {}
};


export default awsmobile;
